# Generated by Django 4.2.5 on 2023-09-08 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_admin_answer_login_words_remove_user_age_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="user", new_name="userinfo",),
    ]
